create:
  name: rtal_attack
  num_classes: 10

remove:
  name: rtal_removal
  epochs: 100

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

optimizer:
  name: Adam
  lr: 0.0001


true_labels: False
name: rtal
output_dir: outputs/cifar10/attacks/rtal/